CREATE TABLE "GCG_6497_REL_UNITS_ASGD" PAGESIZE=4096 (
 "UNIT_ID" INTEGER,
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6),
 "QTY_RELEASED" INTEGER,
 "DATE_RELEASED" CHAR(6),
 "USER_RELEASED" CHAR(6) );